### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/call_summary_bot#1]
- [x] Add basic webhook bot
- [x] Record attendees joining
- [x] Record messages with `-` and `*` as tasks
- [x] (Temporary) post summary as text into the chat
    - [x] #4
- [x] Allow multiple secrets to be defined
